[package]
name = "nit"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
flate2 = { version = "1.1.5", default-features = false, features = ["zlib"] }
hex = "0.4.3"
sha1 = "0.10.6"
